// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// GetContent provides a mock function with given fields: url, definitionContent
func (_m *API) GetContent(url string, definitionContent string) ([]map[string]string, error) {
	ret := _m.Called(url, definitionContent)

	var r0 []map[string]string
	if rf, ok := ret.Get(0).(func(string, string) []map[string]string); ok {
		r0 = rf(url, definitionContent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(url, definitionContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContentFromFileDefinition provides a mock function with given fields: url, definitionPath
func (_m *API) GetContentFromFileDefinition(url string, definitionPath string) ([]map[string]string, error) {
	ret := _m.Called(url, definitionPath)

	var r0 []map[string]string
	if rf, ok := ret.Get(0).(func(string, string) []map[string]string); ok {
		r0 = rf(url, definitionPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(url, definitionPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
