// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LookAheadParser is an autogenerated mock type for the LookAheadParser type
type LookAheadParser struct {
	mock.Mock
}

// apply provides a mock function with given fields: expression
func (_m *LookAheadParser) apply(expression string) []string {
	ret := _m.Called(expression)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(expression)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
