// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: def, content
func (_m *Parser) Parse(def *collector.definition, content string) ([]map[string]string, error) {
	ret := _m.Called(def, content)

	var r0 []map[string]string
	if rf, ok := ret.Get(0).(func(*collector.definition, string) []map[string]string); ok {
		r0 = rf(def, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*collector.definition, string) error); ok {
		r1 = rf(def, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
